### ISSUE TITLE
only add global prefix, not displayName

### ISSUE THREAD

**Issue by Adeher** [unicorn-standard/react-pacomo#1]
Hi, this lib you made really looks like what I need for my app except that I only need to prefix classnames with a global name.
When you also add the displayName in the prefix it makes working on my .less files a pain, even with the "&" trick, because of the sometimes necessary nesting.
My objective is to be able to prefix all classNames with "foo-" and use "postcss-class-prefix" plugin to automatically prefix all my generated CSS.

Also, is there a way to make pacomo work on third party components, like react-bootstrap components ? because their css will get prefixed by postcss but not by pacomo :(

**Comment by amccloud** [comment]
I sorta need the exact opposite. I'd like to not have the module prefix. Maybe modify withPackageName to take a function that returns the prefix?

``` js
// Without displayName
const { decorator, transformer } = withPackageName((displayName) => 'module');

// Without module name
const { decorator, transformer } = withPackageName((displayName) => displayName);

// With both
const { decorator, transformer } = withPackageName((displayName) => `module-${displayName}`);
```

**Comment by jamesknelson** [comment]
@Adeher While you can get away with just prefixing class names with a global name, I'd definitely recommend using component names too - otherwise, you miss out on most of the benefit. Adding component names to the namespace ensures that you can re-use the same class names anywhere in your application.

You mention that nesting is an issue - could you provide an example of where this is the case? I've used nesting successfully with pacomo, for example this component:

``` jsx
render() {
    const {shape, children, ...other} = this.props

    return (
      <div {...other} className={shape}>
        <div className="inner">
          {children}
        </div>
      </div>
    )
  }
```

``` less
.cloth-Paper {
  &-rounded {
    border-radius: 2px;
  }
  &-rounded > &-inner {
    border-radius: 2px;
  }

  /* ... */
}
```

Regarding other libraries, you can just apply the decorator to existing libraries in a separate file somewhere. Just use it as a function instead of a decorator:

``` jsx
import { pacomoDecorator } from '../utils/pacomo';

import { SomeComponent as SomeComponentOriginal } from 'some-library';
export const SomeComponent = pacomoDecorator(SomeComponentOriginal);
```

**Comment by jamesknelson** [comment]
@amccloud I like the proposed syntax! I'm not sure about omitting the module name, though. In what context would you be naming classes like that? An application? A library?

**Comment by amccloud** [comment]
In an application

**Comment by Adeher** [comment]
@jamesknelson : thanks for the reply
I don't want to use components name because as of right now it implies changing too much code in my already developped app, whereas global app prefix + postcss auto prefixing would be really quick. I agree with you it's not the best choice, but it's what I can deal with here. The syntax @amccloud suggested would be awesome.

As for nested .less declarations, it gets messier when going deeper in the nested tree (it generally is a bad idea but you always have special cases)

Regarding the function for applying to other libs, that's great, I'll test it right away.

Great job on this lib anyway, it's an approach I can see myself using, compared to CSS Modules.

**Comment by Adeher** [comment]
To clarify nested CSS, here is an example I often use:

``` less
.my-form {
  .my-input {
    background: #fff;
    &:hover {
      background: #ccc;
    }
    &.disabled {
      background: #666;
    }
  }
}
```

The `disabled` class will get prefixed by pacomo, and I don't see how I can keep that logic using the `&-` trick

**Comment by jamesknelson** [comment]
@Adeher The reason pacomo encourages namespacing with both the package and component name is so you don't need this type of nesting. Assuming the above CSS is for a single component, you'd do something like this:

``` less
.app-MyForm {
  &-input {
    background: #fff;

    &:hover {
      background: #ccc;
    }
  }

  &-input-disabled {
    background: #666;
  }
}
```

As long as `app-MyForm-input-disabled` appears after `app-MyForm-input` in your `className` prop, it will have priority. Of course, if you don't namespace your modifiers by component (e.g. `app-disabled`), this isn't practical.

I'm interested in the ability to use a function to define the namespace. But re: nesting, making this easier would kind of defeat the entire point of pacomo.

**Comment by Adeher** [comment]
You're right, I'm just not used to spliting the classes this way but it's not that big a deal.
Anyway you already did a great job, I tried a few weeks ago to find a way to prefix all classNames through a Babel plugin but with no luck.

Regarding third party components, your solution works most of the time, some components with default props may call other components by themselves (like Input calling FormGroup) but I'm sure it's be enough.

**Comment by dryoma** [comment]
It really might be nice to be able to omit app name, component name, and maybe customize delimiters (say, use underscores instead of a dashes, though I personally prefer dashes).

**Comment by jamesknelson** [comment]
@dryoma Omitting the app name or component name open up class names to conflicts between components or packages, which would kind of defeat the purpose of pacomo. I'm not opposed to a configurable className prefixer, although I'd want it to be a separate package which `react-pacomo` makes use of, not part of `react-pacomo` itself.

Re: custom delimiters, the convention with CSS seems to be dashes, so I'm happy staying with them.

**Comment by jamesknelson** [comment]
If somebody wants to do the work to extract the prefixer to a separate package and make it configurable, I'd be happy to make use of that package from react-pacomo. Closing this for the moment.
