### ISSUE TITLE
Update Peer Dependencies in package.json

### ISSUE THREAD

**Issue by MDSLKTR** [unicorn-standard/react-pacomo#16]
Hey there,

would it be possible to replace

`
  "peerDependencies": {
    "react": "^0.14.0"
  },
`

with

`
  "peerDependencies": {
    "react": "^0.14.0 || ^15.0.2"
  },
`

in your package.json as it is currently breaking my build process as i depend on this build of react:
https://facebook.github.io/react/downloads.html

Thanks in advance,
Simon

**Comment by MDSLKTR** [comment]
any reaction to this would be really helpful, if you're busy right now would be more than understandable.

**Comment by jamesknelson** [comment]
Got it on my list to merge it this weekend, hang in there for another couple days

**Comment by MDSLKTR** [comment]
Sure thing man, thank you for your reply.

**Comment by jamesknelson** [comment]
Merged #17 and released 0.5.2. Thanks @MDSLKTR!
