### ISSUE TITLE
React Warning needs to pass props

### ISSUE THREAD

**Issue by vagasvau** [unicorn-standard/react-pacomo#18]
When using react 15.1.0 and passing props like

`
export class ReactBaseComponent extends React.Component {
constructor(props) {
        super(props);
    }
}
`

I get a warning:

> Warning: DecoratedComponent(...): When calling super() in `DecoratedComponent`, make sure to pass up the same props that your component's constructor was passed.

**Comment by jamesknelson** [comment]
To fix this, I need to place the `__pacomoSkip` flag within element._store instead of element.props when possible, as it isn't a property. Will put this into a PR at some point.

**Comment by jamesknelson** [comment]
Actually, I'm not sure this is the same issue. @jellllllle , could you provide a full example?

**Comment by vagasvau** [comment]
I had an opportunity to dig into the problem a little bit more. It looks like the fault was mine. Some components didnt pass on the props well enough, resulting in a props null value. This eventually caused the warning. issue closed :0
