### ISSUE TITLE
BEM support?

### ISSUE THREAD

**Issue by acjay** [unicorn-standard/react-pacomo#7]
This seems like a very well done project. But it would be nice if it did directly support some notion of BEM. Realistically, some components just have complexity from an element perspective. And I'd argue that fragmenting an entire design into tiny components isn't necessarily a win, especially if the pieces aren't truly atomic.  One of the philosophical wins of BEM was that it identified that some elements (in their parlance) don't really stand alone. 

Rather than recursively chaining things, the element concept keeps the namespace under blocks flat, which is nice because it makes refactoring a block more or less independent of where its elements are internally.

It doesn't appear to me that much is being saved by not having an element concept. You still have to assign a name to the pieces of each component.

**Comment by acjay** [comment]
Actually, I may have misunderstood what was meant by recursing over the children. I originally thought the manual meant the DOM fragment within the `render` method, but now I'm imagining that it means the children assigned in the parent component.

Also, I would add that versus react-bem, this library already seems to have some ergonomic advantages, so it seems to me that it's potentially a shorter road getting this to BEMfullness than making react-bem match the design of this library.

**Comment by jamesknelson** [comment]
@acjay While BEM may provide benefit in some cases, in the majority of cases I've seen the same problems can be better solved by refactoring to use smaller components, and more of them. The other issue with increasing complexity of the transform is that it decreases performance - and especially so if you're using large components (which AFAIK will take longer to transform).

As such, I'd prefer to keep this library simple and leave BEM for another library.
