### ISSUE TITLE
Transformer not working for stateless functions

### ISSUE THREAD

**Issue by bharrisaplus** [unicorn-standard/react-pacomo#8]
It seems that using a stateless function, as defined in [React 0.14](https://facebook.github.io/react/docs/reusable-components.html) allows for a syntax like this:

``` javascript
import React from 'react'
import {pacomoTransformer} from '../utils/pacomo.js'

const Input = ({onChangeHandler, placeHolderValue}) => {
  <div>
    <textarea
      className={`content`}
      onChange={onChangeHandler}
      placeHolder={placeHolder}
    />
  </div>
}

Input.displayName = 'App'

export default pacomoTransformer(Input);
```

However I get an error saying pacomo can't find a render function? Is this something that can be changed as I'd really like to use this syntax.

**Comment by jamesknelson** [comment]
@Shadeslayer345 I think your issue here is that you're using braces without a return statement. Either remove the `{` and `}`, or use `return`.

Closing, but feel free to re-open if this doesn't solve it.

**Comment by oldmill1** [comment]
Does anyone know how to do this with a class?
